# Generated by Django 3.2.17 on 2023-03-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='consult_pending',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
