# Generated by Django 4.1.1 on 2022-12-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medadd', models.CharField(max_length=100)),
                ('medowner', models.CharField(max_length=50)),
                ('medcontact', models.CharField(max_length=20)),
                ('medshop', models.CharField(max_length=100)),
                ('medname', models.CharField(max_length=100)),
                ('medextra', models.CharField(max_length=50)),
                ('medpow', models.CharField(max_length=100)),
                ('medquan', models.CharField(max_length=50)),
                ('medexp', models.CharField(max_length=100)),
            ],
        ),
    ]
