# Generated by Django 3.2.17 on 2023-02-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmastore', '0005_productgalllery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgalllery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
        migrations.AlterField(
            model_name='productgalllery',
            name='image',
            field=models.ImageField(max_length=255, upload_to='store/products'),
        ),
    ]
